spring:
  application:
    name: what_need
  ai:
    ollama:
      ollama:
        chat:
          model: gemma4
        base-url: http://localhost:11434
  datasource:
    url: URL
    username: USERNAME
    password: PASSWORD