spring:
  application:
    name: what_need
  ai:
    ollama:
      ollama:
        chat:
          model: MODEL
        base-url: BASE_URL
  datasource:
    url: URL
    username: USERNAME
    password: PASSWORD
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml