-- liquibase formatted sql

-- changeset Sergalas:1782107160106-1
CREATE TABLE loaded_document
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    filename      VARCHAR(255),
    content_hash  VARCHAR(64),
    document_type VARCHAR(10),
    chunk_count   INTEGER,
    loaded_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_loaded_document PRIMARY KEY (id),
    CONSTRAINT unique_document UNIQUE (filename, content_hash)
);
CREATE INDEX IF NOT EXISTS idx_loaded_documents_filename
    ON loaded_document(filename);

-- changeset Sergalas:1782107160106-2
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE vector_store (
    id varchar(255) primary key,
    content TEXT,
    metadata JSON,
    embedding VECTOR(1024)
);
CREATE INDEX IF NOT EXISTS vector_store_hnsw_index
    ON vector_store USING hnsw(embedding vector_cosine_ops)

